# Generated by Django 4.2.3 on 2023-07-20 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]
